<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('contractor_configurations', function (Blueprint $table) {
            // When false, the contractor (client) is blocked from initiating any
            // payment. Used as a temporary lock while a wrong payroll calculation
            // is regenerated by the third-party app. Enabled by default.
            $table->boolean('payment_enabled')->default(true)->after('penalty_exempt');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('contractor_configurations', function (Blueprint $table) {
            $table->dropColumn('payment_enabled');
        });
    }
};
